name: Backend
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Install dependencies
      working-directory: ./BeatMods2
      run: dotnet restore
    - name: Build project
      working-directory: ./BeatMods2
      run: dotnet build
