name: Frontend
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: ls -lAhR
    - name: Install dependencies
      working-directory: $GITHUB_WORKSPACE/BeatMods2-Frontend/
      run: yarn
    - name: Build project
      working-directory: $GITHUB_WORKSPACE/BeatMods2-Frontend/
      run: yarn build
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: ls -lAhR
    - name: Install dependencies
      working-directory: $GITHUB_WORKSPACE/BeatMods2-Frontend/
      run: yarn
    - name: Run lints
      working-directory: $GITHUB_WORKSPACE/BeatMods2-Frontend/
      run: yarn lint
    - name: Check for changed files
      run: git diff --exit-code
